steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mythoria-webapp'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_ZXhjaXRpbmctaWJleC0xMi5jbGVyay5hY2NvdW50cy5kZXYk'
      - '--build-arg'
      - 'CLERK_SECRET_KEY=sk_test_OzLRy8KzN94cyMmQQSWE2TYKUo8JvWdfnso4dBkbda'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/'
      - '--build-arg'
      - 'NEXTAUTH_SECRET=your-development-secret'
      - '--build-arg'
      - 'NEXTAUTH_URL=https://mythoria.pt'
      - '--build-arg'
      - 'DB_HOST=10.19.192.3'
      - '--build-arg'
      - 'DB_PORT=5432'
      - '--build-arg'
      - 'DB_USER=postgres'
      - '--build-arg'
      - 'DB_PASSWORD=Mythoria1GCould'
      - '--build-arg'
      - 'DB_NAME=mythoria_db'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/mythoria-webapp'

  # Deploy container image to Cloud Run with VPC egress
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mythoria-webapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mythoria-webapp'
      - '--region'
      - 'europe-west9'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--vpc-egress'
      - 'all-traffic'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_ZXhjaXRpbmctaWJleC0xMi5jbGVyay5hY2NvdW50cy5kZXYk,CLERK_SECRET_KEY=sk_test_OzLRy8KzN94cyMmQQSWE2TYKUo8JvWdfnso4dBkbda,NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in,NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up,NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/,NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/,NEXTAUTH_SECRET=your-development-secret,NEXTAUTH_URL=https://mythoria-webapp-803421888801.europe-west9.run.app,DB_HOST=10.19.192.3,DB_PORT=5432,DB_USER=postgres,DB_PASSWORD=Mythoria1GCould,DB_NAME=mythoria_db'

images:
  - 'gcr.io/$PROJECT_ID/mythoria-webapp'
