# Updated Cloud Run service configuration with corrected environment variables
# Key changes:
# 1. CLERK_WEBHOOK_SIGNING_SECRET → CLERK_WEBHOOK_SECRET 
# 2. Removed NEXTAUTH_SECRET and NEXTAUTH_URL (legacy)
# 3. Ensured all Clerk environment variables are correctly named

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mythoria-webapp
  namespace: '803421888801'
  labels:
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: europe-west9
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: updated-config
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
        run.googleapis.com/vpc-access-egress: all-traffic
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 803421888801-compute@developer.gserviceaccount.com
      containers:
      - name: mythoria-webapp-1
        image: gcr.io/oceanic-beach-460916-n5/mythoria-webapp
        ports:
        - name: http1
          containerPort: 3000
        env:
        # Core application settings
        - name: NODE_ENV
          value: production
          
        # Database configuration
        - name: DB_HOST
          value: 10.19.192.3
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: Mythoria1GCould
        - name: DB_NAME
          value: mythoria_db
          
        # Clerk Authentication (CORRECTED)
        - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          value: pk_live_Y2xlcmsubXl0aG9yaWEucHQk
        - name: CLERK_SECRET_KEY
          value: sk_live_8L3AhdA8zaS5FSXSZFcyJDbwlt0F2os7pXmtfNJ6mj
        - name: CLERK_WEBHOOK_SECRET  # FIXED: was CLERK_WEBHOOK_SIGNING_SECRET
          value: whsec_yC4gwWqgOTLRsPwhQMYp5ApvxfL+5lK7
        - name: NEXT_PUBLIC_CLERK_IS_DEVELOPMENT
          value: 'false'
        - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
          value: /sign-in
        - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
          value: /sign-up
        - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
          value: /
        - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
          value: /
          
        # Application settings
        - name: INITIAL_USER_CREDITS
          value: '5'
        - name: NEXT_PUBLIC_SHOW_SOON_PAGE
          value: 'false'
          
        # NOTE: Removed legacy NextAuth variables:
        # - NEXTAUTH_SECRET (not needed for Clerk)
        # - NEXTAUTH_URL (not needed for Clerk)
        
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000
  traffic:
  - percent: 100
    latestRevision: true
