export const revolutErrorMessageToCode: Record<string, string> = {
  "Expired card. Please double check the expiration date or try another card":
    "expired_card",
  "Insufficient funds": "insufficient_funds",
  "Invalid card number": "invalid_card",
  "Invalid CVV": "invalid_cvv",
  "Invalid expiry date": "invalid_expiry",
  "Card reported lost or stolen": "pick_up_card",
  "Payment declined due to suspected fraud": "suspected_fraud",
  "Technical error occurred": "technical_error",
  "Card issuer declined the payment": "issuer_decline",
  "Payment was cancelled by the cardholder": "rejected_by_customer",
  "This transaction is not allowed": "transaction_not_allowed",
  "Authentication required": "authentication_required",
  "Invalid billing address": "invalid_address",
  "Invalid phone number": "invalid_phone",
  "Invalid email address": "invalid_email",
};

export const revolutErrorCodes = [
  "3ds_challenge_failed_manually",
  "insufficient_funds",
  "transaction_not_allowed_for_cardholder",
  "high_risk",
  "cardholder_name_missing",
  "unknown_card",
  "customer_challenge_abandoned",
  "customer_challenge_failed",
  "customer_name_mismatch",
  "do_not_honour",
  "expired_card",
  "invalid_address",
  "invalid_amount",
  "invalid_card",
  "invalid_email",
  "invalid_country",
  "invalid_cvv",
  "invalid_expiry",
  "invalid_merchant",
  "invalid_phone",
  "invalid_pin",
  "issuer_not_available",
  "pick_up_card",
  "rejected_by_customer",
  "restricted_card",
  "technical_error",
  "withdrawal_limit_exceeded",
  "issuer_decline",
  "suspected_fraud",
  "lost_card",
  "stolen_card",
  "security_violation",
  "law_violation",
  "transaction_not_allowed",
  "authentication_required",
  "invalid_account",
  "invalid_transaction",
  "no_such_issuer",
  "currency_not_supported",
  "new_card_not_unblocked",
  "withdrawal_frequency_exceeded",
  "pin_try_exceeded",
  "pin_required",
  "customer_verification_failed",
  "card_not_enrolled_to_three_ds",
  "no_common_supported_three_ds_version",
  "payment_attempt_blocked",
  "unknown",
];

export const mapRevolutError = (message: string): string => {
  const code = revolutErrorMessageToCode[message];
  if (code) return code;
  if (revolutErrorCodes.includes(message)) return message;
  return "unknown";
};
