import type { PaperCutComposition } from '../types';

/**
 * "Kids Fantasy" — the launch paper-cut composition.
 *
 * Layer geometry is expressed in percentages (see ../types.ts). Values are a
 * tuned starting point; nudge them live in the browser. Z-order back→front:
 * back hills (5–6) → mid-ground scenery (7–12) → water/boat (13–15) →
 * girl photo (16) → front hill (17) → bushes (18). All stay < 50 so the
 * sticky frosted header always paints on top.
 *
 * MOBILE TUNING (matches _mockups/Kids_Fantasy_Homepage.png): the `base`
 * breakpoint uses a near-square stage (`1 / 1`) with a LARGE, central girl and
 * tall foreground hills so the diorama fills the stage instead of leaving an
 * empty cream band above it. The `md`/`lg` overrides spread the scene out into
 * a wider, shorter cinematic band on tablet/desktop.
 *
 * ANIMATION (see docs/papercut-animation-guide.md):
 *  - `anim` / `animDurMs` / `animDelayMs` → continuous CSS idle loop.
 *  - `enter` → one-shot fade/slide/scale-in. Delays are staggered back→front so
 *    the diorama "assembles" like a pop-up book. The girl (priority/LCP) has no
 *    enter so she paints instantly.
 *  - `parallax` → scroll-linked travel. `speed` grows with depth (sky & near
 *    foreground move most, distant hills least) to create a sense of depth.
 *  Every animation is automatically disabled under prefers-reduced-motion.
 */
const A = '/homepage/kids_fantasy';

export const kidsFantasy: PaperCutComposition = {
  id: 'kids_fantasy',
  // Mobile = near-square so the big girl fills it (no empty top band).
  // Tablet/desktop = progressively wider, shorter cinematic band.
  stageAspect: { base: '1 / 1', md: '3 / 2', lg: '16 / 6' },

  // --- Sky band: floating decorations behind the headline -------------------
  sky: [
    {
      id: 'balloon',
      src: `${A}/ballon.png`,
      intrinsic: { w: 196, h: 303 },
      z: 4,
      anchor: 'top',
      base: { x: 3, y: 4, width: 16 },
      md: { width: 12 },
      lg: { x: 6, width: 10 },
      shadow: 'sky',
      anim: 'balloon',
      animDurMs: 9000,
      enter: { fromOpacity: 0, fromScale: 0.85, fromY: -10, durationMs: 800 },
      parallax: { speed: -120, fadeOut: true },
    },
    {
      id: 'cloud1',
      src: `${A}/Cloud1.png`,
      intrinsic: { w: 374, h: 256 },
      z: 2,
      anchor: 'top',
      base: { x: -2, y: 20, width: 26 },
      md: { width: 18 },
      lg: { x: 1, width: 14 },
      shadow: 'sky',
      anim: 'drift',
      animDurMs: 13000,
      enter: { fromOpacity: 0, fromX: -30, durationMs: 900, delayMs: 150 },
      parallax: { speed: -60 },
    },
    {
      id: 'cloud2',
      src: `${A}/Cloud2.png`,
      intrinsic: { w: 226, h: 177 },
      z: 2,
      anchor: 'top',
      base: { x: 68, y: 14, width: 20 },
      md: { width: 14 },
      lg: { x: 80, width: 11 },
      shadow: 'sky',
      anim: 'drift',
      animDelayMs: 2000,
      animDurMs: 15000,
      hideBelow: 'sm',
      enter: { fromOpacity: 0, fromX: 30, durationMs: 900, delayMs: 300 },
      parallax: { speed: -80, fadeOut: true },
    },
    {
      id: 'moon',
      src: `${A}/moon1.png`,
      intrinsic: { w: 223, h: 245 },
      z: 3,
      anchor: 'top',
      base: { x: 80, y: 3, width: 15 },
      md: { width: 11 },
      lg: { x: 87, width: 8 },
      shadow: 'sky',
      anim: 'twinkle',
      animDurMs: 6000,
      enter: { fromOpacity: 0, fromScale: 0.7, durationMs: 800, delayMs: 200 },
      parallax: { speed: -40 },
    },
    {
      id: 'star',
      src: `${A}/star1.png`,
      intrinsic: { w: 106, h: 103 },
      z: 3,
      anchor: 'top',
      base: { x: 46, y: 3, width: 8 },
      md: { width: 6 },
      lg: { x: 49, width: 4 },
      shadow: 'none',
      anim: 'twinkle',
      animDelayMs: 800,
      animDurMs: 4500,
      enter: { fromOpacity: 0, fromScale: 0.4, durationMs: 600, delayMs: 450 },
      parallax: { speed: -50 },
    },
  ],

  // --- Scene stage: the diorama --------------------------------------------
  scene: [
    {
      id: 'hill-back-left',
      src: `${A}/small_hill.png`,
      intrinsic: { w: 411, h: 125 },
      z: 5,
      anchor: 'bottom',
      // Tall & raised so its crest peeks above the (lowered) front hill as a
      // distant ridge → the layered-hills look of the mockup.
      base: { x: -16, y: 9, width: 98 },
      lg: { x: -6, y: 6, width: 42 },
      shadow: 'mid',
      enter: { fromOpacity: 0, fromY: 30, durationMs: 700, delayMs: 150 },
      parallax: { speed: -8 },
    },
    {
      id: 'hill-back-right',
      src: `${A}/small_hill.png`,
      intrinsic: { w: 411, h: 125 },
      z: 6,
      anchor: 'bottom',
      base: { x: 42, y: 9, width: 100 },
      lg: { x: 60, y: 5, width: 46 },
      shadow: 'mid',
      enter: { fromOpacity: 0, fromY: 30, durationMs: 700, delayMs: 200 },
      parallax: { speed: -10 },
    },
    {
      id: 'tree-left',
      src: `${A}/tree2.png`,
      intrinsic: { w: 164, h: 348 },
      z: 7,
      anchor: 'bottom',
      base: { x: 4, y: 17, width: 14 },
      lg: { x: 9, y: 12, width: 7 },
      shadow: 'mid',
      anim: 'sway',
      animDelayMs: 1200,
      animDurMs: 9000,
      enter: { fromOpacity: 0, fromY: 24, fromScale: 0.9, durationMs: 650, delayMs: 300 },
      parallax: { speed: -18 },
    },
    {
      id: 'castle',
      src: `${A}/castle.png`,
      intrinsic: { w: 297, h: 430 },
      z: 8,
      anchor: 'bottom',
      // Raised & a touch larger so its towers clearly rise out of the hills.
      base: { x: -3, y: 15, width: 36 },
      md: { width: 24 },
      lg: { x: 3, y: 14, width: 16 },
      shadow: 'mid',
      enter: { fromOpacity: 0, fromY: 28, durationMs: 750, delayMs: 250 },
      parallax: { speed: -15 },
    },
    {
      id: 'trees-cluster',
      src: `${A}/2_trees.png`,
      intrinsic: { w: 261, h: 373 },
      z: 9,
      anchor: 'bottom',
      base: { x: 16, y: 20, width: 23 },
      lg: { x: 16, y: 13, width: 11 },
      shadow: 'mid',
      anim: 'sway',
      animDurMs: 8000,
      enter: { fromOpacity: 0, fromY: 24, durationMs: 700, delayMs: 350 },
      parallax: { speed: -20 },
    },
    {
      id: 'tree-front',
      src: `${A}/tree1.png`,
      intrinsic: { w: 186, h: 362 },
      z: 10,
      anchor: 'bottom',
      base: { x: 28, y: 18, width: 15 },
      lg: { x: 25, y: 12, width: 7 },
      shadow: 'mid',
      anim: 'sway',
      animDelayMs: 600,
      animDurMs: 7000,
      enter: { fromOpacity: 0, fromY: 24, fromScale: 0.9, durationMs: 650, delayMs: 400 },
      parallax: { speed: -24 },
    },
    {
      id: 'dragon',
      src: `${A}/dragon.png`,
      intrinsic: { w: 498, h: 668 },
      z: 9,
      anchor: 'bottom',
      base: { x: 62, y: 12, width: 42 },
      md: { width: 30 },
      lg: { x: 74, y: 11, width: 19 },
      shadow: 'mid',
      anim: 'breathe',
      animDurMs: 6500,
      enter: { fromOpacity: 0, fromY: 30, fromScale: 0.92, durationMs: 800, delayMs: 300 },
      parallax: { speed: -18 },
    },
    {
      id: 'house',
      src: `${A}/house.png`,
      intrinsic: { w: 203, h: 202 },
      z: 11,
      anchor: 'bottom',
      base: { x: 78, y: 13, width: 24 },
      lg: { x: 86, y: 12, width: 11 },
      shadow: 'mid',
      enter: { fromOpacity: 0, fromY: 24, durationMs: 700, delayMs: 400 },
      parallax: { speed: -22 },
    },
    {
      id: 'pathway',
      src: `${A}/pathway.png`,
      intrinsic: { w: 180, h: 149 },
      z: 12,
      anchor: 'bottom',
      base: { x: 80, y: 5, width: 18 },
      lg: { x: 87, y: 6, width: 9 },
      shadow: 'mid',
      enter: { fromOpacity: 0, durationMs: 700, delayMs: 550 },
      parallax: { speed: -30 },
    },
    {
      id: 'boat',
      src: `${A}/pirate_boat.png`,
      intrinsic: { w: 244, h: 273 },
      z: 13,
      anchor: 'bottom',
      base: { x: 0, y: 13, width: 24 },
      lg: { x: 6, y: 9, width: 12 },
      shadow: 'front',
      anim: 'bob',
      animDurMs: 5000,
      enter: { fromOpacity: 0, fromX: -30, fromY: 10, durationMs: 750, delayMs: 450 },
      parallax: { speed: -45 },
    },
    {
      id: 'wave1',
      src: `${A}/wave1.png`,
      intrinsic: { w: 372, h: 125 },
      z: 14,
      anchor: 'bottom',
      base: { x: -4, y: 6, width: 38 },
      lg: { x: 2, y: 5, width: 20 },
      shadow: 'front',
      anim: 'drift',
      animDurMs: 9000,
      enter: { fromOpacity: 0, fromY: 20, durationMs: 600, delayMs: 550 },
      parallax: { speed: -55 },
    },
    {
      id: 'wave2',
      src: `${A}/wave2.png`,
      intrinsic: { w: 252, h: 72 },
      z: 15,
      anchor: 'bottom',
      base: { x: 11, y: 3, width: 24 },
      lg: { x: 11, y: 3, width: 12 },
      shadow: 'front',
      anim: 'drift',
      animDelayMs: 1000,
      animDurMs: 7000,
      hideBelow: 'sm',
      enter: { fromOpacity: 0, fromY: 16, durationMs: 600, delayMs: 650 },
      parallax: { speed: -65 },
    },
    {
      id: 'wave3',
      src: `${A}/wave3.png`,
      intrinsic: { w: 316, h: 79 },
      z: 14,
      anchor: 'bottom',
      base: { x: -2, y: 10, width: 28 },
      lg: { x: 3, y: 8, width: 14 },
      shadow: 'sky',
      anim: 'drift',
      animDelayMs: 500,
      animDurMs: 11000,
      hideBelow: 'sm',
      enter: { fromOpacity: 0, fromY: 16, durationMs: 600, delayMs: 600 },
      parallax: { speed: -50 },
    },
    {
      id: 'girl',
      src: `${A}/GirlHoldingBook.png`,
      intrinsic: { w: 308, h: 512 },
      altKey: 'hero.alt.girl',
      z: 16,
      anchor: 'bottom',
      // Big & central on mobile so she fills the near-square stage (mockup);
      // shrinks on tablet/desktop as the scene widens.
      base: { x: 50, y: 2, width: 54, center: true },
      md: { width: 34 },
      lg: { width: 19 },
      shadow: 'front',
      priority: true,
      // No `enter` — she is the LCP image and must paint immediately. A gentle
      // parallax keeps her feeling part of the scene.
      parallax: { speed: -8 },
    },
    {
      id: 'hill-front',
      src: `${A}/small_hill.png`,
      intrinsic: { w: 411, h: 125 },
      z: 17,
      anchor: 'bottom',
      // Lowered so it reads as a waist-height foreground ridge (not a dome that
      // buries the mid-ground); the back hills now crest above it.
      base: { x: -12, y: 0, width: 116 },
      lg: { x: -6, y: 0, width: 114 },
      shadow: 'front',
      enter: { fromOpacity: 0, fromY: 36, durationMs: 750, delayMs: 500 },
      parallax: { speed: -40 },
    },
    {
      id: 'bush1',
      src: `${A}/bush1.png`,
      intrinsic: { w: 190, h: 104 },
      z: 18,
      anchor: 'bottom',
      base: { x: 0, y: 0, width: 28 },
      lg: { x: 7, y: 0, width: 14 },
      shadow: 'front',
      anim: 'sway',
      animDurMs: 6000,
      enter: { fromOpacity: 0, fromY: 30, durationMs: 650, delayMs: 600 },
      parallax: { speed: -70 },
    },
    {
      id: 'bush2',
      src: `${A}/bush2.png`,
      intrinsic: { w: 180, h: 99 },
      z: 18,
      anchor: 'bottom',
      base: { x: 42, y: 0, width: 26 },
      lg: { x: 44, y: 0, width: 13 },
      shadow: 'front',
      anim: 'sway',
      animDelayMs: 700,
      animDurMs: 6500,
      enter: { fromOpacity: 0, fromY: 30, durationMs: 650, delayMs: 700 },
      parallax: { speed: -75 },
    },
    {
      id: 'bush3',
      src: `${A}/bush3.png`,
      intrinsic: { w: 197, h: 92 },
      z: 18,
      anchor: 'bottom',
      base: { x: 72, y: 0, width: 28 },
      lg: { x: 79, y: 0, width: 14 },
      shadow: 'front',
      anim: 'sway',
      animDelayMs: 1400,
      animDurMs: 7000,
      enter: { fromOpacity: 0, fromY: 30, durationMs: 650, delayMs: 650 },
      parallax: { speed: -80 },
    },
  ],

  text: {
    headlineKey: 'hero.headline',
    subtitleKey: 'hero.subtitle',
    subtitleEmphasizedKey: 'hero.subtitleEmphasized',
    ctaKey: 'hero.tellYourOwnStory',
    ctaPath: 'tell-your-story',
  },

  features: [
    {
      id: 'personalized',
      icon: `${A}/book_icon.png`,
      titleKey: 'hero.features.personalized.title',
      descKey: 'hero.features.personalized.desc',
    },
    {
      id: 'meaningful',
      icon: `${A}/heart_icon.png`,
      titleKey: 'hero.features.meaningful.title',
      descKey: 'hero.features.meaningful.desc',
    },
    {
      id: 'occasion',
      icon: `${A}/users_icon.png`,
      titleKey: 'hero.features.occasion.title',
      descKey: 'hero.features.occasion.desc',
    },
  ],
};
