import type { Metadata } from "next";
import { Auth0Provider } from '@auth0/nextjs-auth0';
import GoogleAnalytics from "../components/GoogleAnalytics";
import AnalyticsProvider from "../components/AnalyticsProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mythoria - Tell your own story",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="autumn" lang="en">
      <head>
        <GoogleAnalytics measurementId={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || 'G-86D0QFW197'} />
      </head>
      <body>
        <Auth0Provider>
          <div className="flex flex-col min-h-screen">
            <AnalyticsProvider>
              <main className="flex-grow">{children}</main>
            </AnalyticsProvider>
          </div>
        </Auth0Provider>
      </body>
    </html>
  );
}
