export const SUPPORTED_COUNTRIES = [
  'AF',
  'AO',
  'AR',
  'AT',
  'AU',
  'AZ',
  'BD',
  'BE',
  'BF',
  'BG',
  'BI',
  'BJ',
  'BO',
  'BR',
  'BY',
  'CA',
  'CD',
  'CH',
  'CI',
  'CL',
  'CM',
  'CN',
  'CO',
  'CU',
  'CZ',
  'DE',
  'DK',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'ES',
  'ET',
  'FI',
  'FR',
  'GB',
  'GH',
  'GN',
  'GR',
  'GT',
  'HK',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IN',
  'IQ',
  'IR',
  'IT',
  'JO',
  'JP',
  'KE',
  'KH',
  'KR',
  'KZ',
  'LK',
  'MA',
  'MG',
  'ML',
  'MM',
  'MZ',
  'MX',
  'MY',
  'NE',
  'NG',
  'NL',
  'NO',
  'NP',
  'NZ',
  'PE',
  'PH',
  'PK',
  'PL',
  'PT',
  'QA',
  'RO',
  'RS',
  'RU',
  'RW',
  'SA',
  'SD',
  'SE',
  'SG',
  'SN',
  'SO',
  'SY',
  'TD',
  'TH',
  'TN',
  'TR',
  'TW',
  'TZ',
  'UA',
  'UG',
  'US',
  'UZ',
  'VE',
  'VN',
  'YE',
  'ZA',
  'ZM',
  'ZW',
] as const;

export type SupportedCountry = (typeof SUPPORTED_COUNTRIES)[number];

export const LOCALE_TO_COUNTRY: Record<string, SupportedCountry> = {
  'en-US': 'US',
  'pt-PT': 'PT',
  'es-ES': 'ES',
  'fr-FR': 'FR',
  'de-DE': 'DE',
};

export function localeToCountry(locale: string): SupportedCountry | null {
  return LOCALE_TO_COUNTRY[locale] ?? null;
}

const COUNTRY_NAME_FALLBACKS: Record<SupportedCountry, string> = {
  AF: 'Afghanistan',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BI: 'Burundi',
  BJ: 'Benin',
  BO: 'Bolivia',
  BR: 'Brazil',
  BY: 'Belarus',
  CA: 'Canada',
  CD: 'Democratic Republic of the Congo',
  CH: 'Switzerland',
  CI: "Côte d'Ivoire",
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CU: 'Cuba',
  CZ: 'Czechia',
  DE: 'Germany',
  DK: 'Denmark',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FR: 'France',
  GB: 'United Kingdom',
  GH: 'Ghana',
  GN: 'Guinea',
  GR: 'Greece',
  GT: 'Guatemala',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',
  IR: 'Iran',
  IT: 'Italy',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KH: 'Cambodia',
  KR: 'South Korea',
  KZ: 'Kazakhstan',
  LK: 'Sri Lanka',
  MA: 'Morocco',
  MG: 'Madagascar',
  ML: 'Mali',
  MM: 'Myanmar',
  MZ: 'Mozambique',
  MX: 'Mexico',
  MY: 'Malaysia',
  NE: 'Niger',
  NG: 'Nigeria',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  PE: 'Peru',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PT: 'Portugal',
  QA: 'Qatar',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SN: 'Senegal',
  SO: 'Somalia',
  SY: 'Syria',
  TD: 'Chad',
  TH: 'Thailand',
  TN: 'Tunisia',
  TR: 'Turkey',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  US: 'United States',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VN: 'Vietnam',
  YE: 'Yemen',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

type RegionDisplayNames = {
  of(code: string): string | undefined;
};

type IntlWithDisplayNames = typeof Intl & {
  DisplayNames?: new (
    locales?: string | string[],
    options?: { type: 'region' },
  ) => RegionDisplayNames;
};

export function getCountryOptions(locale: string): Array<{ value: string; label: string }> {
  const IntlDisplay = (Intl as IntlWithDisplayNames).DisplayNames;
  const displayNames = IntlDisplay ? new IntlDisplay([locale], { type: 'region' }) : null;
  const countries = SUPPORTED_COUNTRIES.map((code) => ({
    value: code,
    label: displayNames?.of(code) ?? COUNTRY_NAME_FALLBACKS[code],
  }));
  return countries.sort((a, b) => a.label.localeCompare(b.label, locale));
}
