import type { PaperCutComposition } from '../../types';
import styles from '../shared/animations.module.css';

const A = '/homepage/kids_fantasy';

export const kidsFantasy: PaperCutComposition = {
  id: 'kids_fantasy',
  rootClassName: styles.root,
  stageAspect: { base: '1 / 1', md: '3 / 2', lg: '16 / 6' },

  sky: [
    {
      id: 'balloon',
      src: `${A}/sky_left.webp`,
      intrinsic: { w: 300, h: 465 },
      z: 4,
      anchor: 'top',
      base: { x: -1, y: 18, width: 23 },
      md: { x: 5, y: 22, width: 15 },
      lg: { x: 9, y: 24, width: 9 },
      shadow: 'front',
      anim: 'balloon',
      animDurMs: 9500,
      enter: { fromOpacity: 0, fromScale: 0.86, fromY: -12, durationMs: 750 },
      parallax: { speed: -90, fadeOut: true },
    },
    {
      id: 'cloud-top-left',
      src: `${A}/cloud_left.webp`,
      intrinsic: { w: 460, h: 350 },
      z: 2,
      anchor: 'top',
      base: { x: -7, y: 15, width: 33 },
      md: { x: 1, y: 15, width: 22 },
      lg: { x: 5, y: 15, width: 13 },
      shadow: 'sky',
      anim: 'drift',
      animDelayMs: 1200,
      animDurMs: 14000,
      enter: { fromOpacity: 0, fromX: -28, durationMs: 850, delayMs: 120 },
      parallax: { speed: -42 },
    },
    {
      id: 'cloud-top-right',
      src: `${A}/cloud_right.webp`,
      intrinsic: { w: 489, h: 317 },
      z: 2,
      anchor: 'top',
      base: { x: 82, y: 26, width: 31 },
      md: { x: 80, y: 22, width: 22 },
      lg: { x: 82, y: 18, width: 13 },
      shadow: 'sky',
      anim: 'drift',
      animDelayMs: 2600,
      animDurMs: 15000,
      enter: { fromOpacity: 0, fromX: 28, durationMs: 850, delayMs: 220 },
      parallax: { speed: -52, fadeOut: true },
    },
    {
      id: 'moon',
      src: `${A}/sky_right.webp`,
      intrinsic: { w: 381, h: 418 },
      z: 3,
      anchor: 'top',
      base: { x: 78, y: 6, width: 18 },
      md: { x: 80, y: 5, width: 12 },
      lg: { x: 83, y: 5, width: 8 },
      shadow: 'sky',
      anim: 'arc',
      animDurMs: 18000,
      enter: { fromOpacity: 0, fromScale: 0.76, durationMs: 700, delayMs: 180 },
      parallax: { speed: -36 },
    },
    {
      id: 'stars',
      src: `${A}/sparkles.webp`,
      intrinsic: { w: 328, h: 318 },
      z: 3,
      anchor: 'top',
      base: { x: 50, y: 17, width: 14, center: true },
      md: { y: 13, width: 10 },
      lg: { y: 10, width: 6 },
      shadow: 'none',
      anim: 'twinkle',
      animDelayMs: 700,
      animDurMs: 4800,
      enter: { fromOpacity: 0, fromScale: 0.5, durationMs: 600, delayMs: 380 },
      parallax: { speed: -44 },
    },
  ],

  scene: [
    {
      id: 'background',
      src: `${A}/background.webp`,
      intrinsic: { w: 3840, h: 2160 },
      z: 5,
      anchor: 'bottom',
      base: { x: 50, y: -15, width: 170, center: true },
      md: { y: -20, width: 138 },
      lg: { y: -60, width: 105 },
      shadow: 'mid',
      enter: { fromOpacity: 0, fromY: 24, durationMs: 750, delayMs: 120 },
      parallax: { speed: -10 },
    },
    {
      id: 'dragon',
      src: `${A}/companion_right.webp`,
      intrinsic: { w: 358, h: 480 },
      z: 9,
      anchor: 'bottom',
      base: { x: 70, y: 35, width: 43 },
      md: { x: 70, y: 24, width: 27 },
      lg: { x: 73, y: 18, width: 21 },
      shadow: 'mid',
      anim: 'breathe',
      animDurMs: 6800,
      enter: { fromOpacity: 0, fromY: 28, fromScale: 0.92, durationMs: 780, delayMs: 260 },
      parallax: { speed: -16 },
    },
    {
      id: 'girl',
      src: `${A}/character.webp`,
      intrinsic: { w: 461, h: 717 },
      altKey: 'hero.alt.girl',
      z: 10,
      anchor: 'bottom',
      base: { x: 50, y: 15, width: 54, center: true },
      md: { y: 10, width: 34 },
      lg: { y: 6, width: 22 },
      shadow: 'front',
      priority: true,
      parallax: { speed: -8 },
    },
    {
      id: 'boat',
      src: `${A}/companion_left.webp`,
      intrinsic: { w: 331, h: 330 },
      z: 12,
      anchor: 'bottom',
      base: { x: 1, y: 29, width: 28 },
      md: { x: 7, y: 20, width: 20 },
      lg: { x: 10, y: 20, width: 12 },
      shadow: 'front',
      anim: 'bob',
      animDurMs: 5200,
      enter: { fromOpacity: 0, fromX: -26, fromY: 12, durationMs: 720, delayMs: 420 },
      parallax: { speed: -36 },
    },
    {
      id: 'foreground',
      src: `${A}/foreground.webp`,
      intrinsic: { w: 1920, h: 1080 },
      z: 16,
      anchor: 'bottom',
      base: { x: 50, y: -4, width: 112, center: true },
      md: { y: -24, width: 112 },
      lg: { y: -65, width: 101 },
      shadow: 'front',
      enter: { fromOpacity: 0, fromY: 30, durationMs: 760, delayMs: 500 },
      parallax: { speed: -42 },
    },
  ],

  text: {
    headlineKey: 'hero.headline',
    subtitleKey: 'hero.subtitle',
    subtitleEmphasizedKey: 'hero.subtitleEmphasized',
    ctaKey: 'hero.tellYourOwnStory',
    ctaPath: 'tell-your-story',
  },

  features: [
    {
      id: 'personalized',
      icon: `${A}/feature_personalized_icon.png`,
      titleKey: 'hero.features.personalized.title',
      descKey: 'hero.features.personalized.desc',
    },
    {
      id: 'meaningful',
      icon: `${A}/feature_meaningful_icon.png`,
      titleKey: 'hero.features.meaningful.title',
      descKey: 'hero.features.meaningful.desc',
    },
    {
      id: 'occasion',
      icon: `${A}/feature_occasion_icon.png`,
      titleKey: 'hero.features.occasion.title',
      descKey: 'hero.features.occasion.desc',
    },
  ],
};
